import { Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import User from '../models/User.js';
import { protect } from '../middleware/auth.js';
const router = Router();
const tokenFor = user => jwt.sign({ id: user._id }, process.env.JWT_SECRET, { expiresIn: '7d' });
router.post('/register', async (req, res, next) => { try { const { name, email, password, role } = req.body; if (!name || !email || !password) return res.status(400).json({ message: 'Name, email and password are required.' }); if (password.length < 8) return res.status(400).json({ message: 'Password must be at least 8 characters.' }); if (await User.exists({ email: email.toLowerCase() })) return res.status(409).json({ message: 'An account with that email already exists.' }); const count = await User.countDocuments(); const user = await User.create({ name, email, password: await bcrypt.hash(password, 12), role: count === 0 ? (role === 'operator' ? 'operator' : 'admin') : 'operator' }); res.status(201).json({ token: tokenFor(user), user: user.toSafeObject() }); } catch (e) { next(e); } });
router.post('/login', async (req, res, next) => { try { const user = await User.findOne({ email: req.body.email?.toLowerCase() }); if (!user || !(await bcrypt.compare(req.body.password || '', user.password))) return res.status(401).json({ message: 'Invalid email or password.' }); res.json({ token: tokenFor(user), user: user.toSafeObject() }); } catch (e) { next(e); } });
router.get('/me', protect, (req, res) => res.json({ user: req.user.toSafeObject() }));
export default router;